//CAKE SHOP
export const BUY_CAKE = 'BUY_CAKE';

//ICECREAM SHOP
export const BUY_ICE_CREAM = 'BUY_ICE_CREAM';

//POST USER_ACTIONS
export const USER_POST_FETCH_LOADING = 'USER_POST_FETCH_LOADING';
export const USER_POST_FETCH_SUCCESS = 'USER_POST_FETCH_SUCCESS';
export const USER_POST_FETCH_ERROR = 'USER_POST_FETCH_ERROR';

//GET USER_ACTIONS
export const USER_FETCH_LOADING = 'USER_FETCH_LOADING';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_ERROR = 'USER_FETCH_ERROR';

//UPDATE USER_PROFILE
export const UPDATE_USER_PROFILE_LOADING = 'UPDATE_USER_PROFILE_LOADING';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_ERROR = 'UPDATE_USER_PROFILE_ERROR';

//DELETE USER_PROFILE
export const DELETE_USER_PROFILE_LOADING = 'DELETE_USER_PROFILE_LOADIN';
export const DELETE_USER_PROFILE_SUCCESS = 'DELETE_USER_PROFILE_SUCCESS';
export const DELETE_USER_PROFILE_ERROR = 'DELETE_USER_PROFILE_ERROR';
